name: Spotless and Build

on:
  workflow_dispatch:
  push: 
    branches:
      - "main"

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up mirror
        run: |
          sed -i -E 's|https://raw.githubusercontent.com/Wynntils/Static-Storage/[0-9a-z]+|https://gitea.com/wuki/Static-Storage/raw/branch/main|g' common/src/main/resources/assets/wynntils/urls.json

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Cache Gradle data
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle--${{ hashFiles('**/settings.gradle', '**/gradle.properties') }}

      - name: Format with spotless
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: spotlessApply

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: buildDependents -x spotlessCheck

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-forge+MC-*.jar
            **/build/libs/*-quilt+MC-*.jar
          if-no-files-found: error

      - name: Genrate release tag
        run: |
          echo "RELEASE_TAG=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
          touch release.txt
          echo "Mirror" >> release.txt

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: release.txt
          files: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-forge+MC-*.jar
            **/build/libs/*-quilt+MC-*.jar
