name: Spotless and Build

on:
  workflow_dispatch:
  push: 
    branches:
      - "main"

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up mirror
        run: |
          sed -i -E 's|https://raw.githubusercontent.com/Wynntils/WynntilsWebsite-API/[0-9a-z]+|https://gitea.com/wuki/WynntilsWebsite-API/raw/branch/master|g' common/src/main/resources/assets/wynntils/urls.json
          sed -i -E 's|https://raw.githubusercontent.com/Wynntils/Reference/[0-9a-z]+|https://gitea.com/wuki/Reference/raw/branch/main|g'  common/src/main/resources/assets/wynntils/urls.json

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Cache Gradle data
        uses: actions/cache@v3
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle--${{ hashFiles('**/settings.gradle', '**/gradle.properties') }}

      - name: Format with spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessApply

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildDependents -x spotlessCheck

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-forge+MC-*.jar
            **/build/libs/*-quilt+MC-*.jar
          if-no-files-found: error

      - name: Genrate release tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          commits=$(curl -s "https://api.github.com/repos/Wynntils/Artemis/commits?per_page=5" | jq -r '.[].commit.message')
          echo "### Changelogs:" >> release.txt
          echo "$commits" | while IFS= read -r line; do
            echo "- $line" >> release.txt
          done

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-forge+MC-*.jar
            **/build/libs/*-quilt+MC-*.jar
