name: Spotless and Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up mirror
        run: |
          sed -i -E 's|https://raw\.githubusercontent\.com/Wynntils/WynntilsWebsite-API/[0-9a-z]+|https://bitbucket.org/wynntils/wynntilswebsite-api/raw/master|g' common/src/main/resources/assets/wynntils/urls.json
          sed -i 's|https://raw\.githubusercontent\.com/Wynntils/Reference|https://bitbucket.org/wynntils/Reference/raw|g' common/src/main/resources/assets/wynntils/urls.json

      - name: Cat
        run: |
          cat common/src/main/resources/assets/wynntils/urls.json
